apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-book-service
spec:
  ingressClassName: nginx
  rules:
    - host: book.local
      http:
        paths:
          - path: /version
            pathType: Prefix
            backend:
              service:
                name: fastapi-book-service
                port:
                  number: 8000
