apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
data:
  DATABASE_URL: "postgresql+asyncpg://postgres:supersecret@postgres-service.default.svc.cluster.local:5432/books_db"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.monitoring.svc.cluster.local:9092"
  
  



