global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "book-service"
    static_configs:
      - targets: ["book-service:8000"]
      