apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-book-service
  template:
    metadata:
      labels:
        app: fastapi-book-service
    spec:
      containers:
        - name: fastapi-book-service
          image: fastapi-book-service:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: book-service-config
            - secretRef:
                name: postgres-secret

          env:
            - name: OTEL_SERVICE_NAME
              value: "fastapi-book-service"

            - name: OTEL_TRACES_EXPORTER
              value: "otlp"

            - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
              value: "http://jaeger-collector.monitoring:4317"
            
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"




    


